load("//third_party/java:rules.bzl", "java_testng_test")

package(default_visibility = ["//visibility:public"])

java_testng_test(
    name = "all_tests",
    size = "small",
    srcs = [
        "ApplicationModelTest.java",
        "ArtifactModelTest.java",
        "ExcludeModelTest.java",
        "GlobalExcludeModelTest.java",
        "OptionsModelTest.java",
        "ReplacementModelTest.java",
        "RepositoryModelTest.java",
        "package-info.java",
    ],
    test_classes = [
        "org.realityforge.bazel.depgen.model.ApplicationModelTest",
        "org.realityforge.bazel.depgen.model.ArtifactModelTest",
        "org.realityforge.bazel.depgen.model.ExcludeModelTest",
        "org.realityforge.bazel.depgen.model.GlobalExcludeModelTest",
        "org.realityforge.bazel.depgen.model.OptionsModelTest",
        "org.realityforge.bazel.depgen.model.ReplacementModelTest",
        "org.realityforge.bazel.depgen.model.RepositoryModelTest",
    ],
    deps = [
        "//src/main/java/org/realityforge/bazel/depgen",
        "//src/test/java/org/realityforge/bazel/depgen:test_support",
        "//third_party/java:gir_core",
        "//third_party/java:testng",
    ],
)
