load("//third_party/java:rules.bzl", "java_binary", "java_library")
load("//tools/release:release.bzl", "release_config_properties")

package(default_visibility = ["//visibility:public"])

DEPGEN_EXTERNAL_DEPS = [
    "//third_party/java:commons_codec",
    "//third_party/java:commons_lang3",
    "//third_party/java:getopt4j",
    "//third_party/java:guava",
    "//third_party/java:httpclient",
    "//third_party/java:httpcore",
    "//third_party/java:javax_inject",
    "//third_party/java:jcl_over_slf4j",
    "//third_party/java:maven_artifact",
    "//third_party/java:maven_builder_support",
    "//third_party/java:maven_model",
    "//third_party/java:maven_model_builder",
    "//third_party/java:maven_repository_metadata",
    "//third_party/java:maven_resolver_api",
    "//third_party/java:maven_resolver_connector_basic",
    "//third_party/java:maven_resolver_impl",
    "//third_party/java:maven_resolver_provider",
    "//third_party/java:maven_resolver_spi",
    "//third_party/java:maven_resolver_transport_file",
    "//third_party/java:maven_resolver_transport_http",
    "//third_party/java:maven_resolver_util",
    "//third_party/java:maven_settings",
    "//third_party/java:maven_settings_builder",
    "//third_party/java:plexus_cipher",
    "//third_party/java:plexus_component_annotations",
    "//third_party/java:plexus_interpolation",
    "//third_party/java:plexus_sec_dispatcher",
    "//third_party/java:plexus_utils",
    "//third_party/java:slf4j_api",
    "//third_party/java:slf4j_jdk14",
    "//third_party/java:snakeyaml",
]

release_config_properties(
    name = "config_properties",
)

java_library(
    name = "core",
    srcs = [
        "Constants.java",
        "DepGenConfig.java",
        "DepgenConfigurationException.java",
        "DepgenException.java",
        "DepgenValidationException.java",
        "package-info.java",
    ],
    resources = [":config_properties"],
    deps = [
        "//src/main/java/org/realityforge/bazel/depgen/util:ordered_properties",
    ],
)

java_library(
    name = "dependency_graph_emitter",
    srcs = [
        "DependencyGraphEmitter.java",
    ],
    deps = [
        ":core",
        "//src/main/java/org/realityforge/bazel/depgen/model",
        "//third_party/java:maven_resolver_api",
        "//third_party/java:maven_resolver_util",
    ],
)

java_library(
    name = "depgen",
    srcs = [
        "AddCommand.java",
        "Command.java",
        "CommandContextImpl.java",
        "CompileAndRuntimeDependencySelector.java",
        "ConfigurableCommand.java",
        "DependencyConfigEditor.java",
        "Environment.java",
        "ExitCodes.java",
        "ExternalAnnotationsDownloaderVisitor.java",
        "GenerateCommand.java",
        "HashCommand.java",
        "InfoCommand.java",
        "InitCommand.java",
        "Main.java",
        "OptionalDependencySelector.java",
        "PeerArtifactDownloaderVisitor.java",
        "PrintGraphCommand.java",
        "RawFormatter.java",
        "RejectDependencySelector.java",
        "RemoveCommand.java",
        "Resolver.java",
        "ResolverUtil.java",
        "SettingsUtil.java",
        "SimpleRepositoryListener.java",
        "SimpleTransferListener.java",
        "SourceDownloaderVisitor.java",
        "TerminalStateException.java",
        "UpdateCommand.java",
    ],
    resources = [
        "//src/main/resources/org/realityforge/bazel/depgen/templates:dependencies.yml",
    ],
    exports = [
        ":core",
        ":dependency_graph_emitter",
        "//src/main/java/org/realityforge/bazel/depgen/config",
        "//src/main/java/org/realityforge/bazel/depgen/metadata",
        "//src/main/java/org/realityforge/bazel/depgen/model",
        "//src/main/java/org/realityforge/bazel/depgen/record",
        "//src/main/java/org/realityforge/bazel/depgen/util",
    ],
    deps = DEPGEN_EXTERNAL_DEPS + [
        ":core",
        ":dependency_graph_emitter",
        "//src/main/java/org/realityforge/bazel/depgen/config",
        "//src/main/java/org/realityforge/bazel/depgen/metadata",
        "//src/main/java/org/realityforge/bazel/depgen/model",
        "//src/main/java/org/realityforge/bazel/depgen/record",
        "//src/main/java/org/realityforge/bazel/depgen/util",
    ],
)

java_binary(
    name = "bazel_depgen",
    main_class = "org.realityforge.bazel.depgen.Main",
    runtime_deps = [":depgen"],
)
