# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
# Since Bazel 0.25, PY3 is the default Python version. Make sure Travis has it.
language: python3
jdk:
  - oraclejdk8
rvm:
  - 2.6.6
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi
    BAZEL_VERSION=$(cat ".bazelversion")
    BAZELISK_VERSION=v1.0
    if [ ! -d "${HOME}/bin" ]; then
      mkdir "${HOME}/bin"
    fi
    wget -O "${HOME}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-${OS}-amd64"
    chmod +x "${HOME}/bin/bazel"
install:
  - gem install bundler
  - bundle install
script: buildr clean package
git:
  depth: 10
