repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.3

  javax_json: org.glassfish:javax.json:jar:1.1

  snakeyaml: org.yaml:snakeyaml:jar:1.24

  gir: org.realityforge.gir:gir-core:jar:0.11

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106
