load("//third_party/java:rules.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "ordered_properties",
    srcs = ["OrderedProperties.java"],
    deps = ["//third_party/java:javax_annotation"],
)

java_library(
    name = "util",
    srcs = [
        "ArtifactUtil.java",
        "BazelUtil.java",
        "Exec.java",
        "GeneratedSectionWriter.java",
        "HashUtil.java",
        "OmitNullRepresenter.java",
        "StarlarkOutput.java",
        "YamlUtil.java",
    ],
    deps = [
        ":ordered_properties",
        "//src/main/java/org/realityforge/bazel/depgen:core",
        "//third_party/java:javax_annotation",
        "//third_party/java:maven_resolver_api",
        "//third_party/java:snakeyaml",
    ],
)
