load("//third_party/java:rules.bzl", "java_library", "java_test")

package(default_visibility = ["//visibility:public"])

TEST_DEPS = [
    "//src/main/java/org/realityforge/bazel/depgen",
    "//third_party/java:commons_codec",
    "//third_party/java:commons_lang3",
    "//third_party/java:getopt4j",
    "//third_party/java:gir_core",
    "//third_party/java:guava",
    "//third_party/java:guiceyloops",
    "//third_party/java:httpclient",
    "//third_party/java:httpcore",
    "//third_party/java:javax_inject",
    "//third_party/java:jcl_over_slf4j",
    "//third_party/java:maven_artifact",
    "//third_party/java:maven_builder_support",
    "//third_party/java:maven_model",
    "//third_party/java:maven_model_builder",
    "//third_party/java:maven_repository_metadata",
    "//third_party/java:maven_resolver_api",
    "//third_party/java:maven_resolver_connector_basic",
    "//third_party/java:maven_resolver_impl",
    "//third_party/java:maven_resolver_provider",
    "//third_party/java:maven_resolver_spi",
    "//third_party/java:maven_resolver_transport_file",
    "//third_party/java:maven_resolver_transport_http",
    "//third_party/java:maven_resolver_util",
    "//third_party/java:maven_settings",
    "//third_party/java:maven_settings_builder",
    "//third_party/java:plexus_cipher",
    "//third_party/java:plexus_component_annotations",
    "//third_party/java:plexus_interpolation",
    "//third_party/java:plexus_sec_dispatcher",
    "//third_party/java:plexus_utils",
    "//third_party/java:slf4j_api",
    "//third_party/java:slf4j_jdk14",
    "//third_party/java:snakeyaml",
    "//third_party/java:testng",
]

TEST_CLASSES = [
    "org.realityforge.bazel.depgen.AddCommandTest",
    "org.realityforge.bazel.depgen.DepGenConfigTest",
    "org.realityforge.bazel.depgen.DependencyGraphEmitterTest",
    "org.realityforge.bazel.depgen.GenerateCommandTest",
    "org.realityforge.bazel.depgen.HashCommandTest",
    "org.realityforge.bazel.depgen.InfoCommandTest",
    "org.realityforge.bazel.depgen.InitCommandTest",
    "org.realityforge.bazel.depgen.MainTest",
    "org.realityforge.bazel.depgen.OptionalDependencySelectorTest",
    "org.realityforge.bazel.depgen.PrintGraphCommandTest",
    "org.realityforge.bazel.depgen.RawFormatterTest",
    "org.realityforge.bazel.depgen.ResolverTest",
    "org.realityforge.bazel.depgen.ResolverUtilTest",
    "org.realityforge.bazel.depgen.SettingsUtilTest",
    "org.realityforge.bazel.depgen.config.ApplicationConfigTest",
    "org.realityforge.bazel.depgen.config.NatureTest",
    "org.realityforge.bazel.depgen.metadata.DepgenMetadataTest",
    "org.realityforge.bazel.depgen.metadata.RecordUtilTest",
    "org.realityforge.bazel.depgen.model.ApplicationModelTest",
    "org.realityforge.bazel.depgen.model.ArtifactModelTest",
    "org.realityforge.bazel.depgen.model.ExcludeModelTest",
    "org.realityforge.bazel.depgen.model.GlobalExcludeModelTest",
    "org.realityforge.bazel.depgen.model.OptionsModelTest",
    "org.realityforge.bazel.depgen.model.ReplacementModelTest",
    "org.realityforge.bazel.depgen.model.RepositoryModelTest",
    "org.realityforge.bazel.depgen.record.ApplicationRecordTest",
    "org.realityforge.bazel.depgen.record.ArtifactRecordTest",
    "org.realityforge.bazel.depgen.util.ArtifactUtilTest",
    "org.realityforge.bazel.depgen.util.BazelUtilTest",
    "org.realityforge.bazel.depgen.util.GeneratedSectionWriterTest",
    "org.realityforge.bazel.depgen.util.HashUtilTest",
    "org.realityforge.bazel.depgen.util.OrderedPropertiesTest",
    "org.realityforge.bazel.depgen.util.StarlarkOutputTest",
    "org.realityforge.bazel.depgen.util.YamlUtilTest",
]

java_library(
    name = "test_support",
    srcs = [
        "AbstractTest.java",
        "JarFileAction.java",
        "TestHandler.java",
        "package-info.java",
    ],
    deps = TEST_DEPS,
)

java_test(
    name = "all_tests",
    size = "large",
    timeout = "long",
    srcs = [
        "AddCommandTest.java",
        "DepGenConfigTest.java",
        "DependencyGraphEmitterTest.java",
        "GenerateCommandTest.java",
        "HashCommandTest.java",
        "InfoCommandTest.java",
        "InitCommandTest.java",
        "MainTest.java",
        "OptionalDependencySelectorTest.java",
        "PrintGraphCommandTest.java",
        "RawFormatterTest.java",
        "ResolverTest.java",
        "ResolverUtilTest.java",
        "SettingsUtilTest.java",
    ],
    args = [
        "-testclass",
        ",".join(TEST_CLASSES),
    ],
    env_inherit = ["PATH"],
    main_class = "org.testng.TestNG",
    use_testrunner = False,
    deps = TEST_DEPS + [
        ":test_support",
        "//src/test/java/org/realityforge/bazel/depgen/config:config_tests",
        "//src/test/java/org/realityforge/bazel/depgen/metadata:metadata_tests",
        "//src/test/java/org/realityforge/bazel/depgen/model:model_tests",
        "//src/test/java/org/realityforge/bazel/depgen/record:record_tests",
        "//src/test/java/org/realityforge/bazel/depgen/util:util_tests",
    ],
)
