load("//third_party/java:rules.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "metadata",
    srcs = [
        "DepgenMetadata.java",
        "RecordBuildCallback.java",
        "RecordUtil.java",
        "package-info.java",
    ],
    deps = [
        "//src/main/java/org/realityforge/bazel/depgen:core",
        "//src/main/java/org/realityforge/bazel/depgen/model",
        "//src/main/java/org/realityforge/bazel/depgen/util",
        "//src/main/java/org/realityforge/bazel/depgen/util:ordered_properties",
        "//third_party/java:maven_resolver_api",
    ],
)
